from django.db import models

# Create your models here.

class BrregEnhet(models.Model):

    organisasjonsnummer = models.IntegerField(primary_key=True)
    navn = models.CharField(max_length=128)
    organisasjonsformkode = models.CharField(max_length=4)
    organisasjonsformbeskrivelse = models.CharField(max_length=64)
    postadresseland = models.CharField(max_length=64, blank=True, null=True)
    postadresselandkode = models.CharField(max_length=10, blank=True, null=True)
    postadressepostnummer = models.IntegerField(blank=True, null=True)
    postadressepoststed = models.CharField(max_length=24, blank=True, null=True)
    postadresseadresse0 = models.CharField(max_length=64, blank=True, null=True)
    postadressekommune = models.CharField(max_length=15, blank=True, null=True)
    postadressekommunenummer = models.IntegerField(blank=True, null=True)
    registreringsdatoenhetsregisteret = models.DateField()
    registrertimvaregisteret = models.CharField(max_length=5)
    naeringskode1beskrivelse = models.CharField(max_length=109, blank=True, null=True)
    naeringskode1kode = models.DecimalField(max_digits=6, decimal_places=3, blank=True, null=True)
    naeringskode2beskrivelse = models.CharField(max_length=71, blank=True, null=True)
    naeringskode2kode = models.DecimalField(max_digits=6, decimal_places=3, blank=True, null=True)
    antallansatte = models.IntegerField()
    forretningsadresseland = models.CharField(max_length=20, blank=True, null=True)
    forretningsadresselandkode = models.CharField(max_length=4, blank=True, null=True)
    forretningsadressepostnummer = models.IntegerField(blank=True, null=True)
    forretningsadressepoststed = models.CharField(max_length=64, blank=True, null=True)
    forretningsadresseadresse0 = models.CharField(max_length=64, blank=True, null=True)
    forretningsadresseadresse1 = models.CharField(max_length=64, blank=True, null=True)
    forretningsadressekommune = models.CharField(max_length=64, blank=True, null=True)
    forretningsadressekommunenummer = models.IntegerField(blank=True, null=True)
    stiftelsesdato = models.CharField(max_length=20, blank=True, null=True)
    institusjonellsektorkodekode = models.IntegerField(blank=True, null=True)
    institusjonellsektorkodebeskrivelse = models.CharField(max_length=128, blank=True, null=True)
    registrertiforetaksregisteret = models.CharField(max_length=5)
    registrertistiftelsesregisteret = models.CharField(max_length=5)
    registrertifrivillighetsregisteret = models.CharField(max_length=5)
    sisteinnsendteaarsregnskap = models.IntegerField(blank=True, null=True)
    konkurs = models.CharField(max_length=5)
    underavvikling = models.CharField(max_length=5)
    undertvangsavviklingellertvangsopplosning = models.CharField(max_length=5)
    maalform = models.CharField(max_length=20)
    postadresseadresse1 = models.CharField(max_length=64, blank=True, null=True)
    hjemmeside = models.CharField(max_length=128, blank=True, null=True)
    frivilligmvaregistrertbeskrivelser0 = models.CharField(max_length=64, blank=True, null=True)
    postadresseadresse2 = models.CharField(max_length=64, blank=True, null=True)
    forretningsadresseadresse2 = models.CharField(max_length=64, blank=True, null=True)
    overordnetenhet = models.IntegerField(blank=True, null=True)
    naeringskode3beskrivelse = models.CharField(max_length=64, blank=True, null=True)
    naeringskode3kode = models.DecimalField(max_digits=6, decimal_places=3, blank=True, null=True)
    frivilligmvaregistrertbeskrivelser1 = models.CharField(max_length=64, blank=True, null=True)


