# Generated by Django 3.2 on 2021-04-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrregEnhet',
            fields=[
                ('organisasjonsnummer', models.IntegerField(primary_key=True, serialize=False)),
                ('navn', models.CharField(max_length=128)),
                ('organisasjonsformkode', models.CharField(max_length=4)),
                ('organisasjonsformbeskrivelse', models.CharField(max_length=64)),
                ('postadresseland', models.CharField(blank=True, max_length=64, null=True)),
                ('postadresselandkode', models.CharField(blank=True, max_length=10, null=True)),
                ('postadressepostnummer', models.IntegerField(blank=True, null=True)),
                ('postadressepoststed', models.CharField(blank=True, max_length=24, null=True)),
                ('postadresseadresse0', models.CharField(blank=True, max_length=64, null=True)),
                ('postadressekommune', models.CharField(blank=True, max_length=15, null=True)),
                ('postadressekommunenummer', models.IntegerField(blank=True, null=True)),
                ('registreringsdatoenhetsregisteret', models.DateField()),
                ('registrertimvaregisteret', models.CharField(max_length=5)),
                ('naeringskode1beskrivelse', models.CharField(blank=True, max_length=109, null=True)),
                ('naeringskode1kode', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('naeringskode2beskrivelse', models.CharField(blank=True, max_length=71, null=True)),
                ('naeringskode2kode', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('antallansatte', models.IntegerField()),
                ('forretningsadresseland', models.CharField(blank=True, max_length=20, null=True)),
                ('forretningsadresselandkode', models.CharField(blank=True, max_length=4, null=True)),
                ('forretningsadressepostnummer', models.IntegerField(blank=True, null=True)),
                ('forretningsadressepoststed', models.CharField(blank=True, max_length=64, null=True)),
                ('forretningsadresseadresse0', models.CharField(blank=True, max_length=64, null=True)),
                ('forretningsadresseadresse1', models.CharField(blank=True, max_length=64, null=True)),
                ('forretningsadressekommune', models.CharField(blank=True, max_length=64, null=True)),
                ('forretningsadressekommunenummer', models.IntegerField(blank=True, null=True)),
                ('stiftelsesdato', models.CharField(blank=True, max_length=20, null=True)),
                ('institusjonellsektorkodekode', models.IntegerField(blank=True, null=True)),
                ('institusjonellsektorkodebeskrivelse', models.CharField(blank=True, max_length=128, null=True)),
                ('registrertiforetaksregisteret', models.CharField(max_length=5)),
                ('registrertistiftelsesregisteret', models.CharField(max_length=5)),
                ('registrertifrivillighetsregisteret', models.CharField(max_length=5)),
                ('sisteinnsendteaarsregnskap', models.IntegerField(blank=True, null=True)),
                ('konkurs', models.CharField(max_length=5)),
                ('underavvikling', models.CharField(max_length=5)),
                ('undertvangsavviklingellertvangsopplosning', models.CharField(max_length=5)),
                ('maalform', models.CharField(max_length=20)),
                ('postadresseadresse1', models.CharField(blank=True, max_length=64, null=True)),
                ('hjemmeside', models.CharField(blank=True, max_length=128, null=True)),
                ('frivilligmvaregistrertbeskrivelser0', models.CharField(blank=True, max_length=64, null=True)),
                ('postadresseadresse2', models.CharField(blank=True, max_length=64, null=True)),
                ('forretningsadresseadresse2', models.CharField(blank=True, max_length=64, null=True)),
                ('overordnetenhet', models.IntegerField(blank=True, null=True)),
                ('naeringskode3beskrivelse', models.CharField(blank=True, max_length=64, null=True)),
                ('naeringskode3kode', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('frivilligmvaregistrertbeskrivelser1', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
